### ISSUE TITLE
Turtle visualizer stops on larger sequence values

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#364] opened 2024-06-28 18:57 UTC
If you take a sequence with integers between 0 and 9 (random, say), and run the turtle visualizer with rules only for 0,1,2,3,4 (the default), it will stop as soon as it reaches a sequence value that is not in that range, with no explanation.  I don't think this is the desired behaviour.  This is an example of invalid parameter inputs that are only defined as invalid on combinations of sequence parameters and visualizer parameters, i.e. won't be checked by either visualizer parameters or sequence parameters alone.   I assume the desired behaviour is that the visualizer should handle such things gracefully.

**Comment by gwhitney** [comment] 2024-07-11 18:22
I mean, it is the designed/implemented behavior. But I agree, it's a pretty unuseful one. However, at first glance the fix might seem to be to automatically mod the sequence entries to be in range, but since the current design allows the domain to be something like `-1, 1` (which is actually used in the Featured Gallery, and I think is a real feature) there is not a clear canonical choice of how to do this. Suppose that the domain had been specified to be `2, 4, 8` and you observe 16 after a while. Which domain element do you choose?

I definitely support the idea of improving this, but it needs design as part of a Turtle overhaul and I think you have a lot of material for that, so we should revisit when that happens.

**Comment by gwhitney** [comment] 2024-08-28 06:12
Some means of addressing this should be part of the Turtle overhaul in progress.

**Comment by gwhitney** [comment] 2024-10-25 02:55
This is handled in #404 and close to a duplicate of #76 anyway, so closing.

**Closed by gwhitney** 2024-10-25 02:55 UTC
Labels: bug, visualizer
