### ISSUE TITLE
this.seq.first and this.seq.last error on OEIS A006577

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#409] opened 2024-07-27 23:09 UTC
On the sequence https://oeis.org/A006577, nothing in ui2 works (none of the visualizers) since we are receiving

`this.seq.first = Infinity` and `this.seq.last = -Infinity`

**Comment by gwhitney** [comment] 2024-07-29 18:29
Closing as duplicate of #407.

**Closed by gwhitney** 2024-07-29 18:29 UTC
Labels: bug, ui, sequence
