### ISSUE TITLE
docsite layout issue -- text obscured

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#179] opened 2022-10-30 00:38 UTC
See the screenshot from Chrome on Ubuntu, where the path at the top of the text panel is half-obscured even when fully scrolled "up".  This doesn't happen on Firefox in Ubuntu.
![Screenshot from 2022-10-29 18-36-18](https://user-images.githubusercontent.com/15117097/198857583-0a7e50b4-a5fe-4164-a816-1236c784d4c2.png)

**Comment by gwhitney** [comment] 2022-11-15 21:01
Can't reproduce on Chrome on OpenSUSE Tumbleweed; is the problem still present, and can anyone reproduce? Thanks!

**Comment by liammulh** [comment] 2022-11-28 17:17
I can't reproduce on my Mac + Chrome. I tried messing with the dimensions of my window using the dev tools, and I wasn't able to reproduce.

**Comment by gwhitney** [comment] 2024-04-23 05:35
@katestange 18 months on are you still observing this?

**Comment by katestange** [comment] 2024-04-23 05:43
Here it is on my browser on the numberscope server right now.
![Screenshot from 2024-04-22 23-43-03](https://github.com/numberscope/frontscope/assets/15117097/973633de-b958-4ca5-b704-7bfa6b33f6f0)

**Comment by katestange** [comment] 2024-04-23 05:47
Comparing the screenshots, it looks improved but not gone.  Maybe we should just wait another 18 months.

**Comment by gwhitney** [comment] 2024-04-23 05:49
@Vectornaut I think you are using Ubuntu; can you reproduce? Neither Liam nor I could observe this, so we never made any progress.

**Comment by gwhitney** [comment] 2024-08-28 07:03
I think this was real and a part of the layout issues with the docsite and maybe was only bad on chrome but should be fixed as part of the docsite overhaul for alpha.

**Comment by gwhitney** [comment] 2024-11-14 18:42
Yes, was a CSS problem in main; fixed in ui2 per #486, so closing.

**Closed by gwhitney** 2024-11-14 18:42 UTC
Labels: bug, documentation, ui
