### ISSUE TITLE
New OEIS sequence causes AxiosError: Network Error

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#206] opened 2022-11-18 22:46 UTC
To reproduce:  Pick a totally random A-number the database has not seen before.  Add it as an OEIS sequence.  Wait 1-2 seconds.  Then up pops a "AxiosError:  Network Error".  Reload the page and try adding that OEIS sequence again.  No problems now.

**Comment by gwhitney** [comment] 2024-04-23 05:27
This should be revisited once https://github.com/numberscope/backscope/pull/127 lands and is installed on the production server.

**Comment by gwhitney** [comment] 2024-08-28 07:00
Duplicate of #407, closing.

**Closed by gwhitney** 2024-08-28 07:00 UTC
Labels: bug
