### ISSUE TITLE
Errors in Numberscope while developing should be traceable

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#280] opened 2024-04-21 04:46 UTC
When developing a visualizer and you get an error, instead of going to the console, it goes to a dialog popup.  Which is the desired behaviour we added.  Except that it doesn't say useful info like what line caused the error.  So it's more difficult to debug now.  Is there a way to either let the error info go to the console also, with a line number, or something else?

**Comment by gwhitney** [comment] 2024-04-21 22:36
I second the motion to have a debug mode that just lets the error occur rather than catching it. What I do at the moment is comment out the following lines in main.ts as needed:

```
app.config.errorHandler = e => {
    window.alert(alertMessage(e))
}
```

**Comment by gwhitney** [comment] 2024-08-28 06:34
Closing as a duplicate of #387, which is resolved.

**Closed by gwhitney** 2024-08-28 06:34 UTC
Labels: enhancement, maintenance
