### ISSUE TITLE
documentation images should all link to live demos

### ISSUE THREAD

**Issue by katestange** [numberscope/frontscope#502] opened 2024-11-23 23:05 UTC
I added a few pics to the documentation for ModFill, and right now when you click you get a closeup of the image.  That's nice, but it would also be nice to be able to go to a live demo of each of the images included in the docs.  Should that be a separate link underneath each image for example?

**Comment by gwhitney** [comment] 2024-11-24 00:27
Closing as duplicate of #488. (You can comment there if you think the way the links should be handled should be different.)

**Closed by gwhitney** 2024-11-24 00:27 UTC
Labels: documentation, enhancement
